name: Fetch Metrics
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  fetch-metrics:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kolkata
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp tqdm asyncio
          
      - name: Fetch metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: ${{ vars.ORG }}
        run: |
          python3 actionboard_data_collector.py
          
      - name: Commit and push if changes exist
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/
          git diff --staged --quiet || (git commit -m "Update GitHub Actions metrics" && git push)